---
- name: install the nginx rpm from a remote repo
  yum: name=http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm state=present
  when: ansible_distribution_major_version == '7'

- name: install the nginx rpm from a remote repo
  yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm state=present
  when: ansible_distribution_major_version == '6'

- name: setup nginx
  yum: name={{ nginx_centos7_rpm }} state=present

- name: Delete default nginx conf
  file: dest=/etc/nginx/sites-enabled/default
        state=absent
  notify: nginx reload
  when: nginx_no_default

- name: Delete default nginx conf
  file: dest={{ nginx_conf_dir }}/conf.d/default.conf
        state=absent
  notify: nginx reload
  when: nginx_no_default

- name: put nginx.conf
  template: src=nginx/nginx.conf dest={{ nginx_conf_dir }}/{{ nginx_conf_file }} owner=root group=root mode=0644
  notify: reload nginx
  when: ansible_distribution_major_version == '7'

- name: put nginx.conf
  template: src=nginx/nginx-6.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
  notify: reload nginx
  when: ansible_distribution_major_version == '6'
